BestBuy/ViewModels/ImageUpload/ImageUploadViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BestBuy.ViewModels.Test
{
    public class ImageUploadViewModel
    {
      public IFormFile Image { get; set; }
    }
}

BestBuy/Controllers/ImageUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using BestBuy.ViewModels.Test;
//using SixLabors.ImageSharp;
using DataAccessLayer.DataAccess;
using System.IO;
using Microsoft.Extensions.FileProviders;
using BusinessLayer.Entity;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BestBuy.Controllers
{
    public class ImageUploadController : Controller
    {
        [HttpGet]
        public IActionResult FileUpload()
        {
            return View();
        }


        [HttpPost]
        public IActionResult FileUpload(ImageUploadViewModel model)
        {
            ImageProcessing proc = new ImageProcessing();
            SmartDevices SDve = new SmartDevices();
            int SDveId = 24;
            byte[] imagebyte = proc.ConvertToBytes(model.Image);
            bool? result = SDve.UpdateSmartDevicesImage(imagebyte, SDveId);

            switch (result)
            {
                case true:

                    break;
             default:

                    break;
            }
            return View();
        }
    }
}

BestBuy/Views/ImageUpload/FileUpload.cshtml
@model BestBuy.ViewModels.Test.ImageUploadViewModel

@using (Html.BeginForm("FileUpload", "ImageUpload", FormMethod.Post,
                                                               new { enctype = "multipart/form-data" }))
{
    <label for="file">Product type:</label>
    
    
    
    <input type="file" asp-for="@Model.Image" id="file" style="width: 100%;" />
    <input type="submit" value="Upload" class="submit" />
}